// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WebApplication1ML.Model
{
    public class ModelInput
    {
        [ColumnName("title"), LoadColumn(0)]
        public string Title { get; set; }


        [ColumnName("text"), LoadColumn(1)]
        public string Text { get; set; }


        [ColumnName("subject"), LoadColumn(2)]
        public string Subject { get; set; }


        [ColumnName("date"), LoadColumn(3)]
        public string Date { get; set; }


        [ColumnName("type"), LoadColumn(4)]
        public string Type { get; set; }


    }
}
